import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ICT GRADE 12
 */
public class loginform extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    PreparedStatement st;

    /**
     * Creates new form loginform
     */
    public loginform() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Log-In");
        setLocationRelativeTo(this);
        setResizable(false);
        setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); use for exit
        setResizable(false);
        
        try
        {
            String driver="com.mysql.jdbc.Driver";
            Class.forName(driver);
            con=DriverManager.getConnection("jdbc:mysql://localhost/studentw","root","");
            System.out.print("Connected");
        }catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        us2 = new javax.swing.JTextField();
        ps2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        us2.setFont(new java.awt.Font("Helvetica Neue", 0, 24));
        us2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                us2ActionPerformed(evt);
            }
        });
        jPanel2.add(us2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 250, 60));

        ps2.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        jPanel2.add(ps2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 250, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CLEAR small red.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGIN small red.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 150, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 460, 450));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OG.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void us2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_us2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_us2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    String sql1="Select employee_id, passw, employee_id, status1 from loginform where employee_id='"+us2.getText()+ "' and passw='"+ps2.getText()+ "'";
    try
    {
        st=con.prepareStatement(sql1);
        rs=st.executeQuery();
        int count =0;
        while(rs.next())
        {
            count=count+1;
            
            String a1=rs.getString("status1");
            if(us2.getText().equals(rs.getString("employee_id")) && ps2.getText().equals(rs.getString("passw")) && rs.getString("status1").equals("admin"))
            {
                JOptionPane.showMessageDialog(null,"Welcome Admin");
                AdminForm ab = new AdminForm();
                this.setVisible(false);
                ab.setVisible(true);
            }
            else if(us2.getText().equals(rs.getString("employee_id")) && ps2.getText().equals(rs.getString("passw")) && rs.getString("status1").equals("client"))
            {
                JOptionPane.showMessageDialog(null,"Welcome Teacher ");
                TeacherHomePage ab = new TeacherHomePage();
                this.setVisible(false);
                ab.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Wrong Username or Password");
            }
                
        }
        if(count==0)
        {
            JOptionPane.showMessageDialog(null,"Please Type Your Username And Password");
        }
        
    }
    catch(Exception e)
    {
        
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField ps2;
    private javax.swing.JTextField us2;
    // End of variables declaration//GEN-END:variables
}
