
import java.sql.DriverManager;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vondrew
 */
public class Studentsregform extends javax.swing.JFrame {

    /**
     * Creates new form Studentsregform
     */
    Connection con;
    ResultSet rs;
    PreparedStatement st;
    public Studentsregform() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        setTitle("Add or Register Student"); 
        idhide.setVisible(false);
        jLabel6.setVisible(false);     
        combo1();
        
        try
        {
            String driver="com.mysql.jdbc.Driver";
            Class.forName(driver);
            con=DriverManager.getConnection("jdbc:mysql://localhost/studentw","root","");
            System.out.print("Connected");
        }catch(Exception e)
        {
        }
        UpdTable();
    }
    private void UpdTable()
    {
        String vb4="select stid as Student_ID, fname as First_Name,midname as MI, lname as Last_Name, sec as Section, level as Level, yearlevel  from studentlist order by lname asc";
        try
        {
            st=con.prepareStatement(vb4);
            rs=st.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lname = new javax.swing.JTextField();
        stid = new javax.swing.JTextField();
        midname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        idhide = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        schooly = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lname.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 310, 30));

        stid.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        stid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stidActionPerformed(evt);
            }
        });
        getContentPane().add(stid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 170, 30));

        midname.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        midname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midnameActionPerformed(evt);
            }
        });
        getContentPane().add(midname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SUBMIT.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, -1, 30));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 710, 430));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 690, 520));

        fname.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 310, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOG OUT.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 700, -1, 30));

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 310, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GRADE 11", "GRADE 12" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 110, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UPDATE_1.png"))); // NOI18N
        jLabel6.setText("UPDATE");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 100, 30));
        getContentPane().add(idhide, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("School Year:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, -1));
        getContentPane().add(schooly, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STUDENTS Register Form UPDATED.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void stidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stidActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void midnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midnameActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String vb1 ="insert into studentlist (stid,fname,midname,lname,sec,level,yearlevel) values(?,?,?,?,?,?,?)";
    
        try
        {
            st=con.prepareStatement(vb1);
            st.setString(1,stid.getText());
            st.setString(2,fname.getText());
            st.setString(3,midname.getText());
            st.setString(4,lname.getText());
            st.setString(5,jComboBox1.getSelectedItem().toString());
            st.setString(6,jComboBox2.getSelectedItem().toString());
             st.setString(7,schooly.getText());
            st.execute();
            JOptionPane.showMessageDialog(null,"Succefully Added");
            stid.setText("");
            fname.setText("");
            midname.setText("");
            lname.setText("");
            
        }catch (Exception e)
        {
            
        }
            UpdTable();
    }//GEN-LAST:event_jLabel2MouseClicked
    public void combo1(){
        String cb1 = "Select * from section";
        try
        {
            st=con.prepareStatement(cb1);
            rs=st.executeQuery();
            while(rs.next())
                    {
                        String cd1=rs.getString("sec");
                        jComboBox1.addItem(""+cd1);
                    }
        }
        catch(Exception e)
        {
            
        }
    }
        
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        loginform ab = new loginform();
        this.setVisible(false);
        ab.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    combo1();
    UpdTable();
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row=jTable1.getSelectedRow();
        idhide.setText(jTable1.getModel().getValueAt(row,0).toString());
        stid.setText(jTable1.getModel().getValueAt(row,0).toString());
        fname.setText(jTable1.getModel().getValueAt(row,1).toString());
        midname.setText(jTable1.getModel().getValueAt(row,2).toString());
        lname.setText(jTable1.getModel().getValueAt(row,3).toString());
        jLabel6.setVisible(true);        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    String vb1 ="update studentlist set stid = ?,fname = ?,midname = ?,lname = ?,sec = ?, level = ? where stid = ?";
    
        try
        {
            st=con.prepareStatement(vb1);
            st.setString(1,stid.getText());
            st.setString(2,fname.getText());
            st.setString(3,midname.getText());
            st.setString(4,lname.getText());
            st.setString(5,jComboBox1.getSelectedItem().toString());
            st.setString(6,jComboBox2.getSelectedItem().toString());
            st.setString(7,idhide.getText());
            st.execute();
            JOptionPane.showMessageDialog(null,"Successfully Updated");
            
        }catch (Exception e)
        {
            
        }
            UpdTable();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studentsregform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studentsregform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studentsregform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studentsregform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studentsregform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fname;
    private javax.swing.JTextField idhide;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField midname;
    private javax.swing.JTextField schooly;
    private javax.swing.JTextField stid;
    // End of variables declaration//GEN-END:variables

}
