import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vondrew
 */
public class AdminChecker extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    PreparedStatement st;
    /**
     * Creates new form AdminChecker
     */
    public AdminChecker() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Admin Confirmation");
        setLocationRelativeTo(this);
        setResizable(false);
        setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
        setResizable(false);
        
        try
        {
            String driver="com.mysql.jdbc.Driver";
            Class.forName(driver);
            con=DriverManager.getConnection("jdbc:mysql://localhost/studentw","root","");
            System.out.print("Connected");
        }catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        us2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pw2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        us2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(us2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 230, -1));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        pw2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(pw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 230, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SUBMIT.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CHANGE PASSWORD OLDDD.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 2, 390, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
    String sql1="Select employee_id, passw, employee_id, status1 from loginform where employee_id='"+us2.getText()+ "' and passw='"+pw2.getText()+ "'";
    try
    {
        st=con.prepareStatement(sql1);
        rs=st.executeQuery();
        int count =0;
        while(rs.next())
        {
            count=count+1;
            
            String a1=rs.getString("status1");
            if(us2.getText().equals(rs.getString("employee_id")) && pw2.getText().equals(rs.getString("passw")) && rs.getString("status1").equals("admin"))
            {
                JOptionPane.showMessageDialog(null,"Welcome Admin");
                AdminChange ab = new AdminChange();
                AdminForm cb = new AdminForm();
                this.setVisible(false);
                ab.setVisible(true);
                cb.setVisible(false);
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Wrong Username or Password");
            }
        }
        if(count==0)
        {
            JOptionPane.showMessageDialog(null,"Wrong Username or Password");
        }
        
    }
    catch(Exception e)
    {
        
        }
    }//GEN-LAST:event_jLabel4MouseClicked

private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
 String sql1="Select employee_id, passw, employee_id, status1 from loginform where employee_id='"+us2.getText()+ "' and passw='"+pw2.getText()+ "'";
    try
    {
        st=con.prepareStatement(sql1);
        rs=st.executeQuery();
        int count =0;
        while(rs.next())
        {
            count=count+1;
            
            String a1=rs.getString("status1");
            if(us2.getText().equals(rs.getString("employee_id")) && pw2.getText().equals(rs.getString("passw")) && rs.getString("status1").equals("admin"))
            {
                JOptionPane.showMessageDialog(null,"Welcome Admin");
                AdminChange ab = new AdminChange();
                AdminForm cb = new AdminForm();
                this.setVisible(false);
                ab.setVisible(true);
                cb.setVisible(false);
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Wrong Username or Password");
            }
        }
        if(count==0)
        {
            JOptionPane.showMessageDialog(null,"Wrong Username or Password");
        }
        
    }
    catch(Exception e)
    {
        
        }
}//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChecker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pw2;
    private javax.swing.JTextField us2;
    // End of variables declaration//GEN-END:variables
}
