import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JFrame;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class Sanction extends javax.swing.JFrame {
 Connection con;
    ResultSet rs;
    PreparedStatement st;
    /** Creates new form Sanction */
    public Sanction() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Admin Homepage");
        setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
        setResizable(false);
        try
        {
            String driver="com.mysql.jdbc.Driver";
            Class.forName(driver);
            con=DriverManager.getConnection("jdbc:mysql://localhost/studentw","root","");
            System.out.print("Connected");
        }catch(Exception e)
        {
            
        }
      // loaddata();
    }
    //public Sanction(String para1, String fn1, String sec1, String lev1a)
    //{
      //initComponents();
      //sid2.setText(para1);
      //cnamea.setText(fn1);
       //sec2.setText(sec1);
        //lev1.setText(lev1a);
    //}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public void loaddata()
    {
        String sql1="Select * from sanction1 where cat1='ACADEMICS' and sid=?";
    try
    {
        st=con.prepareStatement(sql1);
        st.setString(1, sid2.getText());
        // st.setString(2, yearl.getText());
        rs=st.executeQuery();
        int count =0;
        while(rs.next())
        {
            count=count+1;
            
            f1.setText(rs.getString("first1"));
             s1.setText(rs.getString("second1"));
              t1.setText(rs.getString("third1"));
              f1a.setText(rs.getString("fourth1"));
              r1.setText(rs.getString("remarks1"));
             if(count==1)
             {
            pbtn.setVisible(false);
           updbtn1.setVisible(true);
             }
                 //JOptionPane.showMessageDialog(null,"Please Type Your Username And Password");
        }
        if(count==0)
        {
          // saved();
            pbtn.setVisible(true);
           updbtn1.setVisible(false);
           
        }
        
    }
    catch(Exception e)
    {
        
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        s1 = new javax.swing.JTextField();
        f1 = new javax.swing.JTextField();
        f1a = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        f2a = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        s3 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        f3a = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        r3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        r1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        r2 = new javax.swing.JTextArea();
        pbtn = new javax.swing.JLabel();
        wbtn = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lev1 = new javax.swing.JTextField();
        cnamea = new javax.swing.JTextField();
        sid2 = new javax.swing.JTextField();
        sec2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        yearl = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        updbtn1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s1.setFont(new java.awt.Font("Tahoma", 0, 14));
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 80, -1));

        f1.setFont(new java.awt.Font("Tahoma", 0, 14));
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });
        jPanel1.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 80, -1));

        f1a.setFont(new java.awt.Font("Tahoma", 1, 14));
        f1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1aActionPerformed(evt);
            }
        });
        jPanel1.add(f1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 330, 80, -1));

        t1.setFont(new java.awt.Font("Tahoma", 0, 14));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 80, -1));

        f2.setFont(new java.awt.Font("Tahoma", 1, 14));
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });
        jPanel1.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 80, -1));

        s2.setFont(new java.awt.Font("Tahoma", 0, 14));
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 80, -1));

        t2.setFont(new java.awt.Font("Tahoma", 0, 14));
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 80, -1));

        f2a.setFont(new java.awt.Font("Tahoma", 0, 14));
        f2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2aActionPerformed(evt);
            }
        });
        jPanel1.add(f2a, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, 80, -1));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 80, -1));

        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        jPanel1.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 80, -1));

        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });
        jPanel1.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 80, -1));

        f3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3aActionPerformed(evt);
            }
        });
        jPanel1.add(f3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, 80, -1));

        r3.setColumns(20);
        r3.setRows(5);
        jScrollPane2.setViewportView(r3);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 580, 240, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SUBMIT.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 650, -1, -1));

        r1.setColumns(20);
        r1.setRows(5);
        jScrollPane3.setViewportView(r1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 330, 240, 80));

        r2.setColumns(20);
        r2.setRows(5);
        jScrollPane4.setViewportView(r2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 450, 240, 80));

        pbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SUBMIT.png"))); // NOI18N
        pbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pbtnMouseClicked(evt);
            }
        });
        jPanel1.add(pbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 410, -1, -1));

        wbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SUBMIT.png"))); // NOI18N
        wbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wbtnMouseClicked(evt);
            }
        });
        jPanel1.add(wbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 530, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACADEMICS", "BEHAVIORAL" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 290, 60));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACADEMICS", "BEHAVIORAL" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 290, 60));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACADEMICS", "BEHAVIORAL" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 290, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home 2.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 110, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOG OUT.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 710, -1, -1));
        jPanel1.add(lev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 140, -1));
        jPanel1.add(cnamea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 150, -1));
        jPanel1.add(sid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 150, -1));
        jPanel1.add(sec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("School Year:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setText("Student ID:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel8.setText("Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel9.setText("Section:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));
        jPanel1.add(yearl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 120, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel10.setText("Grade Level:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        updbtn1.setText("UPDATE");
        updbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updbtn1MouseClicked(evt);
            }
        });
        jPanel1.add(updbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 420, -1, -1));

        jButton1.setText("UPDATE");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sanctions Imposed FORM.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_s1ActionPerformed

private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_f1ActionPerformed

private void f1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1aActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_f1aActionPerformed

private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_f2ActionPerformed

private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_s2ActionPerformed

private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_t2ActionPerformed

private void f2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2aActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_f2aActionPerformed

private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_t3ActionPerformed

private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_s3ActionPerformed

private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_f3ActionPerformed

private void f3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3aActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_f3aActionPerformed

private void pbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbtnMouseClicked

           saved();
        
        // loaddata();
        
}//GEN-LAST:event_pbtnMouseClicked

private void updbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updbtn1MouseClicked
String vb1 ="update sanction1 set first1=?, second1=?, third1=?, fourth1=?, remarks1=? where sid=? and yearlevel=?"; 
    try
        
{
    
    st= con.prepareStatement(vb1);
   
     st.setString(1, f1.getText());
      st.setString(2, s1.getText());
       st.setString(3, t1.getText());
        st.setString(4, f1a.getText());
         st.setString(5, r1.getText());
         st.setString(6, sid2.getText());
         st.setString(7, yearl.getText());
             
    st.execute();
     JOptionPane.showMessageDialog(null,"Successfully updated the record");
    
    
}catch (Exception e)
{
    
} 
    loaddata();
}//GEN-LAST:event_updbtn1MouseClicked

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//loaddata();
}//GEN-LAST:event_formWindowOpened

private void wbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wbtnMouseClicked
String vb1 ="insert into sanction1 (cat1,first1,second1,third1,fourth1,remarks1,sid,sname,section1,level1,yearlevel) values (?, ?, ?, ?, ?, ?,?, ?, ?, ?,?)"; 
    try
        
{
    
    st= con.prepareStatement(vb1);
    st.setString(1, jComboBox3.getSelectedItem().toString());
     st.setString(2, f2.getText());
      st.setString(3, s2.getText());
       st.setString(4, t2.getText());
        st.setString(5, f2a.getText());
         st.setString(6, r2.getText());
         st.setString(7, sid2.getText());
         st.setString(8, cnamea.getText());
           st.setString(9, sec2.getText());
             st.setString(10, lev1.getText());
             st.setString(11, yearl.getText());
             
    st.execute();
     JOptionPane.showMessageDialog(null,"Successfully save data");
    
    
}catch (Exception e)
{
    
} 
}//GEN-LAST:event_wbtnMouseClicked

private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
AdminForm ab = new AdminForm();
ab.setVisible(true);
this.setVisible(false);
}//GEN-LAST:event_jLabel5MouseClicked

private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
String vb1 ="insert into sanction1 (cat1,first1,second1,third1,fourth1,remarks1,sid,sname,section1,level1,yearlevel) values (?, ?, ?, ?, ?, ?,?, ?, ?, ?,?)"; 
    try
        
{
    
    st= con.prepareStatement(vb1);
    st.setString(1, jComboBox3.getSelectedItem().toString());
     st.setString(2, f2.getText());
      st.setString(3, s2.getText());
       st.setString(4, t2.getText());
        st.setString(5, f2a.getText());
         st.setString(6, r2.getText());
         st.setString(7, sid2.getText());
         st.setString(8, cnamea.getText());
           st.setString(9, sec2.getText());
             st.setString(10, lev1.getText());
             st.setString(11, yearl.getText());
             
    st.execute();
     JOptionPane.showMessageDialog(null,"Successfully save data");
    
    
}catch (Exception e)
{
    
} 
}//GEN-LAST:event_jLabel2MouseClicked
public  void saved()
{
   String vb1 ="insert into sanction1 (cat1,first1,second1,third1,fourth1,remarks1,sid,sname,section1,level1,yearlevel) values (?, ?, ?, ?, ?, ?,?, ?, ?, ?,?)"; 
    try
        
{
    
    st= con.prepareStatement(vb1);
    st.setString(1, jComboBox1.getSelectedItem().toString());
     st.setString(2, f3.getText());
      st.setString(3, s3.getText());
       st.setString(4, t3.getText());
        st.setString(5, f3a.getText());
         st.setString(6, r3.getText());
         st.setString(7, sid2.getText());
         st.setString(8, cnamea.getText());
           st.setString(9, sec2.getText());
             st.setString(10, lev1.getText());
             st.setString(11, yearl.getText());
             
    st.execute();
     JOptionPane.showMessageDialog(null,"Successfully save data");
    
    
}catch (Exception e)
{
    
} 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sanction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sanction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sanction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sanction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Sanction().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField cnamea;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f1a;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f2a;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f3a;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTextField lev1;
    private javax.swing.JLabel pbtn;
    private javax.swing.JTextArea r1;
    private javax.swing.JTextArea r2;
    private javax.swing.JTextArea r3;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    public static javax.swing.JTextField sec2;
    public static javax.swing.JTextField sid2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JButton updbtn1;
    private javax.swing.JLabel wbtn;
    public static javax.swing.JTextField yearl;
    // End of variables declaration//GEN-END:variables
}
